Application Private Events
Mhdez221993/private-events pull request #1
Opened 2021-06-14 16:39 UTC by Mhdez221993

In this  project we created:

1.  a new private-events Rails app and GitHub repo using Rails command line
2. A descriptive README and link to this project
3. Event and User model
4. association between the event creator (a User) and the event
5.  Controllers and corresponding routes

Set up devise to handle authentication

2021-06-14 20:38 UTC, SajjadAhmad14 commented on app/views/layouts/_header.html.erb
> +      <% end %>
Views should be separate from logic.

2021-06-14 20:38 UTC, SajjadAhmad14 commented on app/views/users/show.html.erb
> +    <% end %>
Views should be separate from logic.

2021-06-14 20:42 UTC, SajjadAhmad14 commented on app/views/devise/mailer/email_changed.html.erb
> +<% end %>
Views should be separate from logic.

2021-06-14 20:45 UTC, SajjadAhmad14 requested changes
# Changes Required :recycle:
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hello, you have been doing a tremendous job so far :ok_hand:
## To Highlight 🎉
- [ ] You have mastered Git Flow.
- [ ] README is professional and includes the necessary info to run the project locally.
## To Improve 🙏
- [ ] Please do not repeat one commit message for multiple commits. It does not look descriptive enough.
- [ ] Events controller should have past events, i.e. @past_events = Event.past_events
- [ ] Events controller should have future_events, i.e. @future_events = Event.future_events
- [ ] You should use model scopes to create @past_events, and @future_events.
- [ ] User show action should list events created by user, i.e. @created_events = current_user.events.
- [ ] User show action should use event model scopes to separate past attended events and events that are upcoming.
- [ ] Please add unit tests for model validations and associations.
- [ ] Please add authentication tests (Rspec + Capybara).
- [ ] Please add integration tests for event management (Rspec + Capybara).
- [ ] Some specs are failing. KIndly fix them.
- [ ] Please see inline comments for reference.
# Optional
- [ ] There should be no logic in views. Please use the helpers directory to define views helpers that use logic and render them in views.
### Happy Coding ☺️

## If you have any questions you can comment here in this PR or can always connect with me on slack ( @Sajjad Ahmad ).

2021-06-15 13:53 UTC, carlos-ssh requested changes
**Hello team! 
your project is really nice!.**

📝**A few changes requested** ‼️:
- Would be great to have instructions for additional installations like: ```rails webpacker:install``` for non-technical people.
![Screen Shot 2021-06-15 at 08 36 13](https://user-images.githubusercontent.com/22258274/122064478-cf43c880-cdb6-11eb-89b1-35a73f19e341.png)

- Kindly remove unused files like json.jbuilder.
- lists events previoulsy attendented by user using event model scope, i.e.``` @past_events = current_user.attended_events.previous ```.
- lists upcoming events previously attended by user using event model scope, i.e. ```@upcoming_events = current_user.attended_events.upcoming ```
- When i try to run tests i have failed examples: ```rspec ./spec/authentication/login_spec.rb:8 # User signs in signs in @user with correct credentials
rspec ./spec/authentication/login_spec.rb:17 # User signs in doesn's sign in user with unregistered account
rspec ./spec/authentication/login_spec.rb:27 # User signs in doesn's sign in user with invalid password
rspec ./spec/authentication/login_spec.rb:37 # User signs in doesn's sign in user with invalid email```

**_Happy Coding!_** 👾👾
@carlos-ssh

2021-06-15 16:07 UTC, BrianSammit approved these changes
STATUS: APPROVED :green_circle: :100: 
---------------
Hello @Mhdez221993 @1v4n4 Great job you did in this project :clap: :+1: 
good job working on the required changes :100: :smile: 
-------------
Now you can merge this branch :1st_place_medal: 
HAPPY CODING !!! :100: 

![200](https://user-images.githubusercontent.com/64173189/122086929-cf00f880-cdc9-11eb-8bb1-b95048f8e1cd.gif)

2021-06-16 17:29 UTC, merged